/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author kraik
 */
public class VisualizeGraph extends javax.swing.JFrame {

    /**
     * Creates new form VisualizeGraph
     */
    public VisualizeGraph() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matrixVisualizeBox = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        cosmeticItem = new javax.swing.JPanel();
        GraphVisualizeBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        toGraphOperationsButton = new javax.swing.JButton();
        backToMainMenuButton = new javax.swing.JButton();

        javax.swing.GroupLayout matrixVisualizeBoxLayout = new javax.swing.GroupLayout(matrixVisualizeBox);
        matrixVisualizeBox.setLayout(matrixVisualizeBoxLayout);
        matrixVisualizeBoxLayout.setHorizontalGroup(
            matrixVisualizeBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        matrixVisualizeBoxLayout.setVerticalGroup(
            matrixVisualizeBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cosmeticItem.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout cosmeticItemLayout = new javax.swing.GroupLayout(cosmeticItem);
        cosmeticItem.setLayout(cosmeticItemLayout);
        cosmeticItemLayout.setHorizontalGroup(
            cosmeticItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        cosmeticItemLayout.setVerticalGroup(
            cosmeticItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        background.add(cosmeticItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 220, 610));

        GraphVisualizeBackground.setBackground(new java.awt.Color(204, 204, 204));
        GraphVisualizeBackground.setBorder(new javax.swing.border.MatteBorder(null));
        GraphVisualizeBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Amount of isles:");
        GraphVisualizeBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        background.add(GraphVisualizeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 810, 500));

        toGraphOperationsButton.setBackground(new java.awt.Color(204, 204, 204));
        toGraphOperationsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toGraphOperationsButton.setForeground(new java.awt.Color(0, 0, 0));
        toGraphOperationsButton.setText("Graph Operations");
        toGraphOperationsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toGraphOperationsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toGraphOperationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGraphOperationsButtonActionPerformed(evt);
            }
        });
        background.add(toGraphOperationsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 150, 50));

        backToMainMenuButton.setBackground(new java.awt.Color(204, 204, 204));
        backToMainMenuButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backToMainMenuButton.setForeground(new java.awt.Color(0, 0, 0));
        backToMainMenuButton.setText("Main Menu");
        backToMainMenuButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backToMainMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToMainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMainMenuButtonMouseClicked(evt);
            }
        });
        backToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenuButtonActionPerformed(evt);
            }
        });
        background.add(backToMainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 130, 50));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toGraphOperationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGraphOperationsButtonActionPerformed
        MatrixOperations graphOperations = new MatrixOperations();
        this.setVisible(false);
        graphOperations.setVisible(true);
    }//GEN-LAST:event_toGraphOperationsButtonActionPerformed

    private void backToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToMainMenuButtonActionPerformed

    private void backToMainMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMainMenuButtonMouseClicked
        Principal mainMenu = new Principal();
        this.setVisible(false);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_backToMainMenuButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizeGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GraphVisualizeBackground;
    private javax.swing.JButton backToMainMenuButton;
    private javax.swing.JPanel background;
    private javax.swing.JPanel cosmeticItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel matrixVisualizeBox;
    private javax.swing.JButton toGraphOperationsButton;
    // End of variables declaration//GEN-END:variables
}
